<?php
$reloadLang = [
    'ar' => 'تحديث',
    'de' => 'Neu Laden',
    'el' => 'Ανανέωση',
    'en' => 'Reload',
    'es' => 'Recargar',
    'fr' => 'Recharger',
    'he' => 'רענן',
    'it' => 'Ricaricare',
    'ja' => 'リロード',
    'pt' => 'Recarregar',
    'ru' => 'Перезагружать',
    'zh' => '刷新'
];
$reload = (isset($_GET['lang']) && isset($reloadLang[$_GET['lang']])) ? $reloadLang[$_GET['lang']] : $reloadLang['en'];
?>
<br />
<img id="captcha-image" class="captcha-image" src="<?=BASE_PATH; ?>/captcha" />
<br />
<a class="captcha-reload" href="#" onclick="document.getElementById('captcha-image').src = '<?=BASE_PATH; ?>/captcha?reload=1'; return false;"><?=$reload; ?></a>
