<?php
$reloadLangAry = [
    'ar' => 'تحديث',
    'de' => 'Neu Laden',
    'el' => 'Ανανέωση',
    'en' => 'Reload',
    'es' => 'Recargar',
    'fr' => 'Recharger',
    'he' => 'רענן',
    'it' => 'Ricaricare',
    'ja' => 'リロード',
    'pt' => 'Recarregar',
    'ru' => 'Перезагружать',
    'zh' => '刷新'
];
$reloadLang = (isset($_GET['lang']) && isset($reloadLangAry[$_GET['lang']])) ? $reloadLangAry[$_GET['lang']] : $reloadLangAry['en'];
?>
<br />
<img id="captcha-image" class="captcha-image" src="<?=BASE_PATH; ?>/captcha" />
<br />
<a class="captcha-reload" href="#" onclick="document.getElementById('captcha-image').src = '<?=BASE_PATH; ?>/captcha?reload=1'; return false;"><?=$reloadLang; ?></a>
